# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:34:45+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Amount(BaseModel):
    convertedFromCurrency: Optional[str] = Field(
        None,
        description='The three-letter <a href="https://www.iso.org/iso-4217-currency-codes.html " target="_blank">ISO 4217</a> code representing the currency of the amount in the <b> convertedFromValue</b> field. This value is the pre-conversion currency.<br><br>This field is only returned if/when currency conversion was applied by eBay. For implementation help, refer to <a href=\'https://developer.ebay.com/api-docs/sell/finances/types/ba:CurrencyCodeEnum\'>eBay API documentation</a>',
    )
    convertedFromValue: Optional[str] = Field(
        None,
        description='The monetary amount before any conversion is performed, in the currency specified by the <b> convertedFromCurrency</b> field. This value is the pre-conversion amount. The <b> value</b> field contains the converted amount of this value, in the currency specified by the <b> currency</b> field.<br><br>This field is only returned if/when currency conversion was applied by eBay.',
    )
    currency: Optional[str] = Field(
        None,
        description="A three-letter ISO 4217 code that indicates the currency of the amount in the <b>value</b> field. This field is always returned with any container using <b>Amount</b> type. <br><br><b>Default</b>: The currency of the authenticated user's country. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/ba:CurrencyCodeEnum'>eBay API documentation</a>",
    )
    exchangeRate: Optional[str] = Field(
        None,
        description='The exchange rate used for the monetary conversion. This field shows the exchange rate used to convert the dollar value in the <b>value</b> field from the dollar value in the <b>convertedFromValue</b> field.<br><br>This field is only returned when eBay does a currency version, and a currency conversion is generally needed if the buyer is viewing, or has purchased an item on an international site. <br><br>This field is only returned if/when currency conversion was applied by eBay.',
    )
    value: Optional[str] = Field(
        None,
        description='The monetary amount, in the currency specified by the <b>currency</b> field. This field is always returned with any container using <b>Amount</b> type.',
    )


class BalanceAdjustment(BaseModel):
    adjustmentAmount: Optional[Amount] = Field(
        None,
        description='The seller payout balance amount that will be applied toward the charges outlined in the <b>charges</b> array.',
    )
    adjustmentType: Optional[str] = Field(
        None,
        description="The enumeration value returned here indicates if the charge is a <code>DEBIT</code> or a <code>CREDIT</code> to the seller. Generally, all transfer transaction types are going to be <code>DEBIT</code>, since the money is being tranferred from the seller to eBay. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )


class Buyer(BaseModel):
    username: Optional[str] = Field(
        None, description="The eBay user ID of the order's buyer."
    )


class Charge(BaseModel):
    cancellationId: Optional[str] = Field(
        None,
        description='The unique identifier of an order cancellation. This field is only applicable and returned if the charge is related to an order  cancellation.',
    )
    caseId: Optional[str] = Field(
        None,
        description='The unique identifier of a case filed against an order. This field is only applicable and returned if the charge is related to a case filed against an order.',
    )
    chargeNetAmount: Optional[Amount] = Field(
        None,
        description='This container shows the net amount of the charge, which is the total amount of the charge minus the total amount of fees credited towards this refund as per eBay policy. It is possible for there to be multiple charges from multiple orders with one transfer. The net aggregate amount for all charges found in the <b>charges</b> array can be found in the <b>transferDetail.totalChargeNetAmount</b> container.',
    )
    inquiryId: Optional[str] = Field(
        None,
        description='The unique identifier of an Item Not Received (INR) inquiry filed against an order. This field is only applicable and returned if the charge is related to has an INR inquiry filed against the order.',
    )
    orderId: Optional[str] = Field(
        None,
        description='The unique identifier of the order that is associated with the charge.',
    )
    paymentDisputeId: Optional[str] = Field(
        None,
        description="The unique identifier of a third-party payment dispute filed against an order. This occurs when the buyer files a dispute against the order with their payment provider, and then the dispute comes into eBay's system. This field is only applicable and returned if the charge is related to a third-party payment dispute filed against an order.",
    )
    refundId: Optional[str] = Field(
        None,
        description='The unique identifier of a buyer refund associated with the charge.',
    )
    returnId: Optional[str] = Field(
        None,
        description='The unique identifier of an order return. This field is only applicable and returned if the charge is related to an order that was returned by the buyer.',
    )


class ErrorParameter(BaseModel):
    name: Optional[str] = Field(None, description='The object of the error.')
    value: Optional[str] = Field(None, description='The value of the object.')


class FeeJurisdiction(BaseModel):
    regionName: Optional[str] = Field(
        None,
        description='String value that indicates the name of the region to which a region-specific fee applies.<br><br>The set of valid <b>regionName</b> values that may be returned is determined by the <b>regionType</b> value.<br><br><span class="tablenote"><strong>Note:</strong> Currently, supported <b>regionName</b> values that may be returned are standard two-character country or state codes.<br><br>Typical examples include:<ul><li><b>MX</b> [Mexico]</li><li><b>IN</b> [India]</li><li><b>US</b> [United States]</li><li>CA [California]</li><li>VT [Vermont]</li><li>ME [Maine]</li></ul></span>',
    )
    regionType: Optional[str] = Field(
        None,
        description="The enumeration value returned here indicates the type of region that is collecting the corresponding fee. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:RegionTypeEnum'>eBay API documentation</a>",
    )


class FundingSource(BaseModel):
    brand: Optional[str] = Field(
        None,
        description='The brand name of the credit card or the name of the financial institution that is the source of payment. This field may not be populated for other funding sources.',
    )
    memo: Optional[str] = Field(
        None,
        description="This field provides a note about the funding source. If the seller's credit card or bank account is the funding source, this field might contain the last four digits of the credit card or bank account. This field may also be returned as null.",
    )
    type: Optional[str] = Field(
        None,
        description="The string value returned here indicates the funding source. Possible values include the following:<ul><li><code>AVAILABLE_FUNDS</code>: transfer is funded with seller payout funds</li><li><code>CREDIT_CARD</code>: transfer is funded with seller's credit card</li><li><code>BANK</code>: transfer is funded with a direct debit to seller's bank account on file with eBay</li><li><code>PAY_UPON_INVOICE</code>: eBay will bill the seller for the transfer on the monthly invoice</li></ul>",
    )


class PayoutInstrument(BaseModel):
    accountLastFourDigits: Optional[str] = Field(
        None,
        description='This value is the last four digits of the account that the seller uses to receive the payout. This may be the last four digits of a bank account, a debit card, or a payment processor account such as Payoneer.',
    )
    instrumentType: Optional[str] = Field(
        None,
        description="This value indicates the type of account that received the payout. The value returned in this field may be:<br><ul><li><code>BANK</code>: indicates that the payout was made to a seller's bank account.</li><li><code>CARD</code>: indicates that the payout went to a seller's debit card</li><li>The name of a digital wallet provider or payment processor (e.g., <code>PAYONEER</code>)</li></ul>",
    )
    nickname: Optional[str] = Field(
        None,
        description='When <b>instrumentType</b> returns <code>BANK</code>, this value is the seller-provided nickname that the seller uses to represent the bank account that receives the payout.<br><br>When <b>instrumentType</b> returns <code>CARD</code>, this value is the debit card network for the debit card that receives the payout.<br><br>When <b>instrumentType</b> returns a provider of digital wallet or payment processing services, the value returned is the name of the service provider (e.g., <code>PAYONEER</code>).',
    )


class PayoutSummaryResponse(BaseModel):
    amount: Optional[Amount] = Field(
        None,
        description='This container shows the total value (and currency type used) of the seller payouts that match the input criteria. This field is not returned if there are no payouts that match the input criteria.',
    )
    payoutCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total count of payouts to the seller that match the input criteria. This field is always returned, even if there are no payouts that match the input criteria (its value will show <code>0</code>).',
    )
    transactionCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total count of monetary transactions (order payments, buyer refunds, and seller credits) associated with the payouts that match the input criteria. This field is always returned, even if there are no payouts that match the input criteria (its value will show <code>0</code>). If there is at least one payout that matches the input criteria, the value in this field will be at least <code>1</code>.',
    )


class Reference(BaseModel):
    referenceId: Optional[str] = Field(
        None,
        description='The identifier of the transaction as specified by the <strong>referenceType</strong>. For example, with a <strong>referenceType</strong> of <strong>item_id</strong>, the <strong>referenceId</strong> refers to a unique item. This item may have several <code>NON_SALE_CHARGE</code> transactions.',
    )
    referenceType: Optional[str] = Field(
        None,
        description="An enumeration value that identifies the reference type associated with the <strong>referenceId</strong>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:ReferenceTypeEnum'>eBay API documentation</a>",
    )


class SellerFundsSummaryResponse(BaseModel):
    availableFunds: Optional[Amount] = Field(
        None,
        description='This field represents the total amount of order funds that are available for a payout, but processing for a seller payout has not yet begun. If a seller wants to get more details on sales transactions that have yet to be processed, the seller can use the <strong>getTransactions</strong> method, and use the <strong>transactionStatus</strong> filter with its value set to <code>FUNDS_AVAILABLE_FOR_PAYOUT</code>.<br><br>This container will return 0.0 with the appropriate payout currency if there are no funds available to be processed for a payout.',
    )
    fundsOnHold: Optional[Amount] = Field(
        None,
        description='This field represents the total amount of order funds on hold. Seller payment holds can occur for different reasons. If a seller wants to get more details on sales transactions where funds are currently on hold, the seller can use the <strong>getTransactions</strong> method, and use the <strong>transactionStatus</strong> filter with its value set to <code>FUNDS_ON_HOLD</code>.<br><br>This container will return 0.0 with the appropriate payout currency if there are no seller payment holds that will eventually be processed for a payout.',
    )
    processingFunds: Optional[Amount] = Field(
        None,
        description='This field represents the total amount of order funds being prepared and processed for a seller payout. If a seller wants to get more details on sales transactions that are being processed, the seller can use the <strong>getTransactions</strong> method, and use the <strong>transactionStatus</strong> filter with its value set to <code>FUNDS_PROCESSING</code>.<br><br>This container will return 0.0 with the appropriate payout currency if there are no funds available to be processed for a payout.',
    )
    totalFunds: Optional[Amount] = Field(
        None,
        description='This field represents the total amount of order funds still due to be distributed to the seller through a seller payout. This field should equal the sum of the amounts returned in the following fields:<br><ul><li><b>processingFunds</b></li><li><b>availableFunds</b></li><li><b>fundsOnHold</b></li></ul><br>If no payout funds are due to the seller, a <code>204 - No Content</code>  status code will be returned along with an empty payload.',
    )


class TransactionSummaryResponse(BaseModel):
    adjustmentAmount: Optional[Amount] = Field(
        None,
        description='Total adjustment amount for given payee within a specified period.',
    )
    adjustmentBookingEntry: Optional[str] = Field(
        None,
        description="The credit debit sign indicator for adjustment. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    adjustmentCount: Optional[int] = Field(
        None,
        description='Total adjustment count for given payee within a specified period.',
    )
    balanceTransferAmount: Optional[Amount] = Field(
        None,
        description='The total balance transfer amount for given payee within the specified period.',
    )
    balanceTransferBookingEntry: Optional[str] = Field(
        None,
        description="The credit debit sign indicator for the balance transfer. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    balanceTransferCount: Optional[int] = Field(
        None,
        description='The total balance transfer count for given payee within the specified period.',
    )
    creditAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total dollar value of all the seller\'s sales and/or credits that match the input criteria. <br><br><span class="tablenote"><strong>Note:</strong> Unless the <b>transactionType</b> filter is used in the request to retrieve a specific type of monetary transaction, the <b>creditCount</b> and <b>creditAmount</b> fields account for both order sales and seller credits (the count and value is not distinguished between the two monetary transaction types).</span><br><br>If there are no sales/credits (<strong>creditCount</strong>=<code>0</code>), this container is not returned.',
    )
    creditBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>creditAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>CREDIT</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    creditCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of the seller\'s sales and/or credits that match the input criteria. <br><br><span class="tablenote"><strong>Note:</strong> Unless the <b>transactionType</b> filter is used in the request to retrieve a specific type of monetary transaction (sale, buyer refund, or seller credit), the <b>creditCount</b> and <b>creditAmount</b> fields account for both order sales and seller credits (the count and value is not distinguished between the two monetary transaction types).</span><br><br>This field is generally returned, even if <code>0</code>, but it will not be returned if a <strong>transactionType</strong> filter is used, and its value is set to either <code>REFUND</code>, <code>DISPUTE</code>, or <code>SHIPPING_LABEL</code>.',
    )
    disputeAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total dollar value associated with any existing payment disputes that have been initiated by one or more buyers. Only the orders that match the input criteria are considered. The Payment Disputes methods in the Fulfillment API can be used by the seller to retrieve more information about any payment disputes.<br><br>If there are no payment disputes (<strong>disputeCount</strong>=<code>0</code>), this container is not returned.',
    )
    disputeBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>disputeAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>DEBIT</code>, but its possible that <code>CREDIT</code> could be returned if the seller contested one or more payment disputes and won the dispute. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    disputeCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of payment disputes that have been initiated by one or more buyers. Only the orders that match the input criteria are considered. The Payment Disputes methods in the Fulfillment API can be used by the seller to retrieve more information about any payment disputes. <br><br>This field is generally returned, even if <code>0</code>, but it will not be returned if a <strong>transactionType</strong> filter is used, and its value is set to any value other than <code>DISPUTE</code>.',
    )
    loanRepaymentAmount: Optional[Amount] = Field(
        None,
        description='The sum of all <code>LOAN_REPAYMENT</code> transactions (i.e., debit and credit,) that match the input criteria.<br><br>For example, within a specified <code>transactionDate</code> range, three <code>LOAN_REPAYMENT</code> transactions are identified:<ul><li>DEBIT of 15.00 USD</li><li>DEBIT of 10.00 USD</li><li>CREDIT of 5.00 USD</li></ul>The net amount of these three transactions is a <i>DEBIT of 20.00 USD</i> to the seller\'s account. Therefore, the value returned for <code>loanRepaymentAmount</code> will be <b>20.00 USD</b>.<br><br><span class="tablenote"><b>Note:</b> For this example:<ul><li>The value returned for <code>loanRepaymentCount</code> will be <b>3</b></li><li>The <code>loanRepaymentBookingEntry</code> will be <b>DEBIT</b></li></ul></span><br><br>If there are no transactions that match the input criteria (i.e., <code>loanRepaymentCount</code>=<b>0</b>,) this container is not returned.',
    )
    loanRepaymentBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the <code>loanRepaymentAmount</code> is a <code>DEBIT</code> against, or a <code>CREDIT</code> to, the sellers's account.<br><br>For most <code>loanRepaymentAmount</code> transactions, <code>loanRepaymentBookingEntry</code> will be <b>DEBIT</b>. However, if a loan repayment transaction is reversed, that transaction will be shown as a <b>CREDIT</b>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    loanRepaymentCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of <code>LOAN_REPAYMENT</code> transactions (i.e., <code>DEBIT</code> and <code>CREDIT</code>,) that match the input criteria.<br><br>This field is generally returned even if it equals <b>0</b>. However it will not be returned if a <code>transactionType</code> filter is used and its value has been set to any enumeration value other than <code>LOAN_REPAYMENT</code>.',
    )
    nonSaleChargeAmount: Optional[Amount] = Field(
        None,
        description='The total non-sale charge amount for given payee within a specified period.',
    )
    nonSaleChargeBookingEntry: Optional[str] = Field(
        None,
        description="The credit/debit sign indicator for the non-sale charge. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    nonSaleChargeCount: Optional[int] = Field(
        None,
        description='The total non-sale charge count for given payee within a specified period.',
    )
    onHoldAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total dollar value of order sales where the associated funds are on hold. Only the orders that match the input criteria are considered.<br><br>If there are no seller payment holds (<strong>onHoldCount</strong>=<code>0</code>), this container is not returned.',
    )
    onHoldBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>onHoldAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>CREDIT</code>, since on-hold funds should eventually be released as part of a payout to the seller once the hold is cleared. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    onHoldCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of order sales where the associated funds are on hold. Only the orders that match the input criteria are considered.<br><br>This field is generally returned, even if <code>0</code>, but it will not be returned if a <strong>transactionStatus</strong> filter is used, and its value is set to any value other than <code>FUNDS_ON_HOLD</code>.',
    )
    refundAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total dollar value of buyer refunds that match the input criteria.<br><br>If there are no refunds (<strong>refundCount</strong>=<code>0</code>), this container is not returned.',
    )
    refundBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>refundAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>DEBIT</code> since this a refund from the seller to the buyer. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    refundCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of buyer refunds that match the input criteria. <br><br>This field is generally returned, even if <code>0</code>, but it will not be returned if a <strong>transactionType</strong> filter is used, and its value is set to any value other than <code>REFUND</code>.',
    )
    shippingLabelAmount: Optional[Amount] = Field(
        None,
        description='This is the total dollar value of the eBay shipping labels purchased by the seller.',
    )
    shippingLabelBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>shippingLabelAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>DEBIT</code>, as eBay will charge the seller when eBay shipping labels are purchased, but it can be <code>CREDIT</code> if the seller was refunded for a shipping label or was possibly overcharged for a shipping label. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    shippingLabelCount: Optional[int] = Field(
        None,
        description='This is the total number of eBay shipping labels purchased by the seller. The count returned here may depend on the specified input criteria.',
    )
    transferAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total dollar value of buyer refund transfers that match the input criteria.<br><br>If there are no transfers (<strong>refundCount</strong>=<code>0</code>), this container is not returned.',
    )
    transferBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>transferAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>DEBIT</code> since this a seller reimbursement to eBay for buyer refunds. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    transferCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of buyer refund transfers that match the input criteria. <br><br>This field is generally returned, even if <code>0</code>, but it will not be returned if a <strong>transactionType</strong> filter is used, and its value is set to any value other than <code>TRANSFER</code>.',
    )
    withdrawalAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total dollar value of on-demand payouts (withdrawals) that match the input criteria.<br><br>If there are no withdrawals (<strong>withdrawalCount</strong>=<code>0</code>), this container is not returned.',
    )
    withdrawalBookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value indicates whether the dollar amount in the <strong>withdrawalAmount</strong> field is a charge (debit) to the seller or a credit. Typically, the enumeration value returned here will be <code>DEBIT</code> since this transaction involves a debit to the seller's available payout funds. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    withdrawalCount: Optional[int] = Field(
        None,
        description='This integer value indicates the total number of on-demand payouts (withdrawals) that match the input criteria. <br><br>This field is generally returned, even if <code>0</code>, but it will not be returned if a <strong>transactionType</strong> filter is used, and its value is set to any value other than <code>WITHDRAWAL</code>.',
    )


class TransferDetail(BaseModel):
    balanceAdjustment: Optional[BalanceAdjustment] = Field(
        None,
        description='This container shows the seller payout balance that will be applied toward the charges outlined in the <b>charges</b> array.',
    )
    charges: Optional[List[Charge]] = Field(
        None,
        description='This container is an array of one or more charges related to the transfer. Charges can be related to an order cancellation, order return, case, payment dispute, etc.',
    )
    totalChargeNetAmount: Optional[Amount] = Field(
        None,
        description='This container shows the total amount that the seller owes for all of the charges outlined in the <b>charges</b> array.',
    )


class Error(BaseModel):
    category: Optional[str] = Field(None, description='Identifies the type of erro.')
    domain: Optional[str] = Field(
        None,
        description='Name for the primary system where the error occurred. This is relevant for application errors.',
    )
    errorId: Optional[int] = Field(
        None, description='A unique number to identify the error.'
    )
    inputRefIds: Optional[List[str]] = Field(
        None,
        description='An array of request elements most closely associated to the error.',
    )
    longMessage: Optional[str] = Field(
        None, description='A more detailed explanation of the error.'
    )
    message: Optional[str] = Field(
        None,
        description="Information on how to correct the problem, in the end user's terms and language where applicable.",
    )
    outputRefIds: Optional[List[str]] = Field(
        None,
        description='An array of request elements most closely associated to the error.',
    )
    parameters: Optional[List[ErrorParameter]] = Field(
        None,
        description='An array of name/value pairs that describe details the error condition. These are useful when multiple errors are returned.',
    )
    subdomain: Optional[str] = Field(
        None,
        description='Further helps indicate which subsystem the error is coming from. System subcategories include: Initialization, Serialization, Security, Monitoring, Rate Limiting, etc.',
    )


class Fee(BaseModel):
    amount: Optional[Amount] = Field(None, description='The amount of the fee.')
    feeJurisdiction: Optional[FeeJurisdiction] = Field(
        None,
        description='Indicates the specific jurisdiction for the fee that has been deducted from the seller payour.',
    )
    feeMemo: Optional[str] = Field(
        None,
        description='A description of the fee that was deducted from the seller payout.',
    )
    feeType: Optional[str] = Field(
        None,
        description="The enumeration value returned here indicates the type of fee that was deducted from the seller payout. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/api:FeeTypeEnum'>eBay API documentation</a>",
    )


class OrderLineItem(BaseModel):
    feeBasisAmount: Optional[Amount] = Field(
        None,
        description='This is the total amount of fees accrued for the order line item and deducted from a seller payout. All of the fees under the <b>marketplaceFees</b> container should equal this amount.',
    )
    lineItemId: Optional[str] = Field(
        None, description='The unique identifier of an order line item.'
    )
    marketplaceFees: Optional[List[Fee]] = Field(
        None,
        description='An array of all fees accrued for the order line item and deducted from a seller payout.',
    )


class Payout(BaseModel):
    amount: Optional[Amount] = Field(
        None,
        description='This the total amount of the seller payout. The container shows the dollar amount of the payout and the currency used. The value of the payout is always shown, even if the payout has failed.',
    )
    bankReference: Optional[str] = Field(
        None,
        description="This field contains additional information provided by the bank and passed on by the payment processor; e.g., the manner in which the transaction will appear on the seller's bank statement. The field is returned only when provided by the bank and processor.",
    )
    lastAttemptedPayoutDate: Optional[str] = Field(
        None,
        description='This timestamp indicates the date/time when eBay last attempted to process a seller payout but it failed. This field is only returned if a seller payout fails, and the <strong>payoutStatus</strong> value shows <code>RETRYABLE_FAILED</code> or <code>TERMINAL_FAILED</code>. A seller can filter on the <b>lastAttemptedPayoutDate</b> in a <b>getPayouts</b> request.',
    )
    payoutDate: Optional[str] = Field(
        None,
        description='This timestamp indicates when the seller payout began processing. The following format is used: <code>YYYY-MM-DDTHH:MM:SS.SSSZ</code>. For example, <code>2015-08-04T19:09:02.768Z</code>. This field is still returned even if the payout was pending but failed (<strong>payoutStatus</strong> value shows <code>RETRYABLE_FAILED</code> or <code>TERMINAL_FAILED</code>).',
    )
    payoutId: Optional[str] = Field(
        None,
        description="The unique identifier of the seller payout. This identifier is generated once eBay begins processing the payout to the seller's bank account.",
    )
    payoutInstrument: Optional[PayoutInstrument] = Field(
        None,
        description="This container provides details about the seller's account that received (or is scheduled to receive) the payout. This container is still returned even if the payout failed.",
    )
    payoutMemo: Optional[str] = Field(
        None,
        description='This field contains information provided by upstream components, based on internal and external commitments. A typical message would contain the expected arrival time of the payout.',
    )
    payoutStatus: Optional[str] = Field(
        None,
        description="This enumeration value indicates the current status of the seller payout. For a successful payout, the value returned will be <code>SUCCEEDED</code>. See the <strong>PayoutStatusEnum</strong> type for more details on each payout status value. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:PayoutStatusEnum'>eBay API documentation</a>",
    )
    payoutStatusDescription: Optional[str] = Field(
        None,
        description="This field provides more details about the current status of payout. The description returned here will correspond with enumeration value returned in the <strong>payoutStatus</strong> field. The following shows what description text might appear based on the different <strong>payoutStatus</strong> values:<ul><li><code>INITIATED</code>: <em>Preparing to send</em></li><li><code>SUCCEEDED</code>: <em>Funds sent</em></li><li><code>REVERSED</code>: <em>Waiting to retry : Money rejected by seller's bank</em></li><li><code>RETRYABLE_FAILED</code>: <em>Waiting to retry</em></li><li><code>TERMINAL_FAILED</code>: <em>Payout failed</em></li></ul>",
    )
    totalAmount: Optional[Amount] = Field(
        None,
        description="This container indicates the sum of a seller's net payout amount plus the <code>EXPRESS_PAYOUT_FEE</code> charged by eBay. The is expressed as a numeric value and the currency used.",
    )
    totalFee: Optional[Amount] = Field(
        None,
        description='This container indicates the amount of the <code>EXPRESS_PAYOUT_FEE</code> charged by eBay when a seller requests payout to a debit card. The fee is expressed as a numeric value and the currency used.',
    )
    transactionCount: Optional[int] = Field(
        None,
        description='This integer value indicates the number of monetary transactions (all orders, refunds, and credits, etc.) that have occurred with the corresponding payout. Its value should always be at least <code>1</code>, since there is at least one order per seller payout.',
    )


class Payouts(BaseModel):
    href: Optional[str] = Field(
        None,
        description='The URI of the <b>getPayouts</b> call request that produced the current page of the result set.',
    )
    limit: Optional[int] = Field(
        None,
        description='The maximum number of payouts that may be returned per page of the result set. The <strong>limit</strong> value can be passed in as a query parameter, or if omitted, its value defaults to <code>20</code>. <br><br><span class="tablenote"><strong>Note:</strong> If this is the last or only page of the result set, the page may contain fewer payouts than the <strong>limit</strong> value.  To determine the number of pages in a result set, divide the <b>total</b> value (total number of payouts matching input criteria) by this <strong>limit</strong> value, and then round up to the next integer. For example, if the <b>total</b> value was <code>120</code> (120 total payouts) and the <strong>limit</strong> value was <code>50</code> (show 50 payouts per page), the total number of pages in the result set is three, so the seller would have to make three separate <strong>getPayouts</strong> calls to view all payouts matching the input criteria. </span><br><br><b>Maximum:</b> <code>200</code> <br> <b>Default:</b> <code>20</code>',
    )
    next: Optional[str] = Field(
        None,
        description='The <b>getPayouts</b> call URI to use if you wish to view the next page of the result set. <br><br>This field is only returned if there is a next page of results to view based on the current input criteria.',
    )
    offset: Optional[int] = Field(
        None,
        description='This integer value indicates the actual position that the first payout returned on the current page has in the results set. So, if you wanted to view the 11th payout of the result set, you would set the <strong>offset</strong> value in the request to <code>10</code>. <br><br>In the request, you can use the <b>offset</b> parameter in conjunction with the <b>limit</b> parameter to control the pagination of the output. For example, if <b>offset</b> is set to <code>30</code> and <b>limit</b> is set to <code>10</code>, the call retrieves payouts 31 thru 40 from the resulting collection of payouts. <br><br> <span class="tablenote"><strong>Note:</strong> This feature employs a zero-based list, where the first item in the list has an offset of <code>0</code>.</span><br><br><b>Default:</b> <code>0</code> (zero)',
    )
    payouts: Optional[List[Payout]] = Field(
        None,
        description='An array of one or more payouts that match the input criteria. Details for each payout include the unique identifier of the payout, the status of the payout, the amount of the payout, and the number of monetary transactions associated with the payout.',
    )
    prev: Optional[str] = Field(
        None,
        description='The <b>getPayouts</b> call URI to use if you wish to view the previous page of the result set. <br><br>This field is only returned if there is a previous page of results to view based on the current input criteria.',
    )
    total: Optional[int] = Field(
        None,
        description='This integer value is the total number of payouts in the results set based on the current input criteria. Based on the total number of payouts that match the criteria, and on the <strong>limit</strong> and <strong>offset</strong> values, there may be additional pages in the results set.',
    )


class Transaction(BaseModel):
    amount: Optional[Amount] = Field(
        None,
        description='This container shows the dollar value and currency type of the monetary transaction. This field is always returned even when eBay has yet to initiate a payout for the order.',
    )
    bookingEntry: Optional[str] = Field(
        None,
        description="The enumeration value returned in this field indicates if the monetary transaction amount is a (<code>CREDIT</code>) or a (<code>DEBIT</code>) to the seller's account. Typically, the <code>SALE</code> and <code>CREDIT</code> transaction types are credits to the seller's account, and the <code>REFUND</code>, <code>DISPUTE</code>, <code>SHIPPING_LABEL</code>, and <code>TRANSFER</code> transaction types are debits to the seller's account. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:BookingEntryEnum'>eBay API documentation</a>",
    )
    buyer: Optional[Buyer] = Field(
        None,
        description='This is the unique eBay user ID for the buyer who purchased the order. This field is not returned for <code>TRANSFER</code> monetary transaction types.',
    )
    eBayCollectedTaxAmount: Optional[Amount] = Field(
        None,
        description='This is the amount of sales tax that has been collected by eBay for an order.<br><br><span class="tablenote"><b>Note:</b> Sales tax applies only to <code>SALE</code> and <code>REFUND</code> transactions (<b>transactionType</b>).</span>',
    )
    feeJurisdiction: Optional[FeeJurisdiction] = Field(
        None,
        description="This container stores information about region-specific fees that are charged to sellers.<br><br>This is returned for fees (i.e., <b>FeeTypeEnum</b> values,) that are mandated by a seller's governing jurisdiction.<br><br>For example:<ul><li><code>INCOME_TAX_WITHHOLDING</code></li><li><code>TAX_DEDUCTION_AT_SOURCE</code></li><li><code>VAT_WITHHOLDING</code></li></ul>",
    )
    feeType: Optional[str] = Field(
        None,
        description="The type of fee. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/api:FeeTypeEnum'>eBay API documentation</a>",
    )
    orderId: Optional[str] = Field(
        None,
        description='The unique identifier of the eBay order associated with the monetary transaction.',
    )
    orderLineItems: Optional[List[OrderLineItem]] = Field(
        None,
        description='This array shows the fees that are deducted from a seller payout for each line item in an order.<br><br><span class="tablenote"><strong>Note:</strong> In some cases, a transaction fee might be returned asynchronously from the associated order. In such cases, you can determine the order to which the fee applies by examining the referenceID value of the fee, which should match the ID of the order.',
    )
    paymentsEntity: Optional[str] = Field(
        None,
        description='This string value indicates the entity that is processing  the payment.',
    )
    payoutId: Optional[str] = Field(
        None,
        description='The unique identifier of the seller payout associated with the monetary transaction. This identifier is generated once eBay begins processing the payout for the corresponding order. This field will not be returned if eBay has not yet begun processing the payout for an order.',
    )
    references: Optional[List[Reference]] = Field(
        None,
        description='This field contains reference information for the transaction fee. This includes an ID and the type of ID provided (such as item ID).',
    )
    salesRecordReference: Optional[str] = Field(
        None,
        description='The Sales Record Number associated with a sales order. Sales Record Numbers are Selling Manager/Selling Manager Pro identifiers that are created at order checkout.<br><br><span class="tablenote"><strong>Note:</strong> For all orders originating after February 1, 2020, a value of <code>0</code> will be returned in this field. The Sales Record Number field has also been removed from Seller Hub. Instead of <strong>salesRecordReference</strong>, depend on <strong>orderId</strong> instead as the identifier of the order. The <strong>salesRecordReference</strong> field has been scheduled for deprecation, and a date for when this field will no longer be returned at all will be announced soon.</span>',
    )
    totalFeeAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total amount of selling fees paid for order. A breakdown of fees for each order line item can be found in the <b>orderLineItems</b> array.<br><br> This field is even returned if it is <code>0.0</code> (no fees deducted from seller payout).',
    )
    totalFeeBasisAmount: Optional[Amount] = Field(
        None,
        description='This amount is the total amount of the order before selling fees are deducted from the seller payout associated with the order. To determine the actual amount of the order that will be paid out through a seller payout, deduct the <b>totalFeeAmount</b> from the <b>basePayoutAmount</b>.',
    )
    transactionDate: Optional[str] = Field(
        None,
        description='This timestamp indicates when the monetary transaction (order purchase, buyer refund, seller credit) occurred. The following (UTC) format is used: <code>YYYY-MM-DDTHH:MM:SS.SSSZ</code>. For example, <code>2015-08-04T19:09:02.768Z</code>.',
    )
    transactionId: Optional[str] = Field(
        None,
        description="The unique identifier of the monetary transaction. A monetary transaction can be a sales order, an order refund to the buyer, a credit to the seller's account, a debit to the seller for the purchase of a shipping label, or a transaction where eBay recouped money from the seller if the seller lost a buyer-initiated payment dispute.",
    )
    transactionMemo: Optional[str] = Field(
        None,
        description='This field provides more details on shipping label transactions and transactions where the funds are being held by eBay. For shipping label transactions, the <b>transactionMemo</b> gives details about a purchase, a refund, or a price adjustment to the cost of the shipping label. For on-hold transactions, the <b>transactionMemo</b> provides information on the reason for the hold or when the hold will be released (e.g., "Funds on hold. Estimated release on Jun 1").<br><br>This field is only returned if applicable/available.',
    )
    transactionStatus: Optional[str] = Field(
        None,
        description="This enumeration value indicates the current status of the seller payout associated with the monetary transaction. See the <code>TransactionStatusEnum</code> type for more information on the different states. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/finances/types/pay:TransactionStatusEnum'>eBay API documentation</a>",
    )
    transactionType: Optional[str] = Field(
        None,
        description='This enumeration value indicates the type of monetary transaction. Examples of monetary transactions include a buyer\'s payment for an order, a refund to the buyer for a returned item or cancelled order, or a credit issued by eBay to the seller\'s account. For a complete list of monetary transaction types within the <strong>Finances API</strong>, see the <a href="/api-docs/sell/finances/types/pay:TransactionTypeEnum">TransactionTypeEnum</a> type. For implementation help, refer to <a href=\'https://developer.ebay.com/api-docs/sell/finances/types/pay:TransactionTypeEnum\'>eBay API documentation</a>',
    )


class Transactions(BaseModel):
    href: Optional[str] = Field(
        None,
        description='The URI of the <b>getTransactions</b> method request that produced the current page of the result set.',
    )
    limit: Optional[int] = Field(
        None,
        description='The maximum number of monetary transactions that may be returned per page of the result set. The <strong>limit</strong> value can be passed in as a query parameter, or if omitted, its value defaults to <code>20</code>. <br><br><span class="tablenote"><strong>Note:</strong> If this is the last or only page of the result set, the page may contain fewer monetary transactions than the <strong>limit</strong> value.  To determine the number of pages in a result set, divide the <b>total</b> value (total number of monetary transactions matching input criteria) by this <strong>limit</strong> value, and then round up to the next integer. For example, if the <b>total</b> value was <code>120</code> (120 total monetary transactions) and the <strong>limit</strong> value was <code>50</code> (show 50 monetary transactions per page), the total number of pages in the result set is three, so the seller would have to make three separate <strong>getTransactions</strong> calls to view all monetary transactions matching the input criteria. </span><br><br><b>Maximum:</b> <code>200</code> <br> <b>Default:</b> <code>20</code>',
    )
    next: Optional[str] = Field(
        None,
        description='The <b>getTransactions</b> method URI to use if you wish to view the next page of the result set. <br><br>This field is only returned if there is a next page of results to view based on the current input criteria.',
    )
    offset: Optional[int] = Field(
        None,
        description='This integer value indicates the actual position that the first monetary transaction returned on the current page has in the results set. So, if you wanted to view the 11th monetary transaction of the result set, you would set the <strong>offset</strong> value in the request to <code>10</code>. <br><br>In the request, you can use the <b>offset</b> parameter in conjunction with the <b>limit</b> parameter to control the pagination of the output. For example, if <b>offset</b> is set to <code>30</code> and <b>limit</b> is set to <code>10</code>, the method retrieves monetary transactions 31 thru 40 from the resulting collection of monetary transactions. <br><br> <span class="tablenote"><strong>Note:</strong> This feature employs a zero-based list, where the first item in the list has an offset of <code>0</code>.</span><br><br><b>Default:</b> <code>0</code> (zero)',
    )
    prev: Optional[str] = Field(
        None,
        description='The <b>getTransactions</b> method URI to use if you wish to view the previous page of the result set. <br><br>This field is only returned if there is a previous page of results to view based on the current input criteria.',
    )
    total: Optional[int] = Field(
        None,
        description='This integer value is the total amount of monetary transactions in the result set based on the current input criteria. Based on the total number of monetary transactions that match the criteria, and on the <strong>limit</strong> and <strong>offset</strong> values, there may be additional pages in the results set.',
    )
    transactions: Optional[List[Transaction]] = Field(
        None,
        description="An array of one or more monetary transactions that match the input criteria. Details for each monetary transaction may include the unique identifier of the order associated with the monetary transaction, the status of the transaction, the amount of the order, the order's buyer, and the unique identifier of the payout (if a payout has been initiated/issued for the order).",
    )


class Transfer(BaseModel):
    fundingSource: Optional[FundingSource] = Field(
        None,
        description="This container provides details about the seller's funding source to reimburse eBay for the transfer, such as a bank account, a credit card, or available seller payout funds.",
    )
    transactionDate: Optional[str] = Field(
        None,
        description='This timestamp indicates the date/time of the transfer. The following (UTC) format is used: <code>YYYY-MM-DDTHH:MM:SS.SSSZ</code>. For example, <code>2020-08-04T19:09:02.768Z</code>',
    )
    transferAmount: Optional[Amount] = Field(
        None,
        description='The amount of the transfer being deducted from the funding source.',
    )
    transferDetail: Optional[TransferDetail] = Field(
        None,
        description='This container provides more details about the transfer, including details on the charge(s) associated with the transfer. Multiple charges can be addressed with one transfer.',
    )
    transferId: Optional[str] = Field(
        None,
        description='The unique identifier of the <code>TRANSFER</code> transaction type. This is the same value that was passed into the end of the call URI.',
    )
